 
DROP TABLE IF EXISTS LOGIN_DATA ; 
DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS EXCLUSION_ACCOUNTS ;
CREATE TABLE LOGIN_DATA (
  ID INT AUTO_INCREMENT  PRIMARY KEY,
  SUBMITTED_BY VARCHAR(10) NOT NULL,
  SUBMITTED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
  APPROVED_BY VARCHAR(10),
  APPROVAL_DATE TIMESTAMP,
  STATUS VARCHAR(10) ,
  ACCOUNT_NUMBER VARCHAR(20) NOT NULL
);

CREATE TABLE USERS (
  ID INT AUTO_INCREMENT  PRIMARY KEY,
  FIRST_NAME VARCHAR(250) NOT NULL,
  LAST_NAME VARCHAR(250) NOT NULL,
  USERNAME VARCHAR(250) DEFAULT NULL,
  PASSWORD VARCHAR(250) DEFAULT NULL,
  ROLE VARCHAR(250) DEFAULT NULL,
  KEY VARCHAR(250) DEFAULT NULL
);

CREATE TABLE EXCLUSION_ACCOUNTS (
  ID INT AUTO_INCREMENT  PRIMARY KEY,
  ACCOUNT_NUMBER VARCHAR(20) NOT NULL
);


 
INSERT INTO LOGIN_DATA (SUBMITTED_BY , APPROVED_BY, STATUS, ACCOUNT_NUMBER) VALUES
  ('tom', '', 'pending', '2000123458');
 
INSERT INTO USERS (FIRST_NAME, LAST_NAME, USERNAME, PASSWORD, ROLE) VALUES
  ('Tom', 'Tom', 'tom', 'tom', 'user'),
  ('John', 'John', 'john', 'john', 'admin');
 
INSERT INTO EXCLUSION_ACCOUNTS (ACCOUNT_NUMBER) VALUES
  ('2000123458'),('5000123460');


    
  
 